### ISSUE TITLE
Cannot reindex repository

### ISSUE THREAD

**Issue by rgreinho** [hypnoglow/helm-s3#131]
Our repository got  re-initialized by mistake (`helm s3 init`) and now we cannot regenerate the index:

```
$ helm s3 reindex team-repo
traverse the chart repository: unserialize chart meta: invalid character '=' looking for beginning of value
Error: plugin "s3" exited with error
```
Versions:
```
$ helm version
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"dirty", GoVersion:"go1.15.5"}
$ helm s3 version
0.10.0
```

Is there a workaround to fix this without having to recreate the repository and re-upload our charts?

**Comment by beatkind** [comment]
Same here

**Comment by Mateuscppoi** [comment]
I don't know if this will help as a workaround or to find exactly the problem, but i had this issue yesterday and the problem was that my chart had some accents (because i'm from brazil and portuguese is a strange language), removing the accents resolved the problem with reindex, this made me belive that the problem can be something to do with the char encode type.
I don't have a lot of experience with go but i will try to test if this is realy the probelm. If (somehow) i managed to fix it i will submit a pr.

**Comment by hypnoglow** [comment]
I believe this should be fixed already. Please try using the latest plugin release.

I'm going to close this issue, feel free to reach out again if you still experience the problem, and please provide the `Chart.yaml` file.
