### ISSUE TITLE
Official Docker Image

### ISSUE THREAD

**Issue by austince** [hypnoglow/helm-s3#79]
Hey there, thanks for the awesome plugin. Has there been any discussion about pre-packaging this with Helm in a Docker image? If not, would that be useful to this community?

**Comment by austince** [comment]
We needed this over at FinTech Studios, so we've published an image here: https://hub.docker.com/r/fintechstudios/helm-s3

Happy to donate this back if you would like!

**Comment by hypnoglow** [comment]
Hi,

This is a great idea. I was using my in-house docker image with this plugin, but haven't added the Dockerfile to this repo yet.

I think I'll include the Dockerfile and the official docker image in the next release.

**Comment by austince** [comment]
Looks great! Is it possible to push a `latest` tag as well so pulling the repository without specifying a tag will work?

```shell script
docker pull hypnoglow/helm-s3

Using default tag: latest
Error response from daemon: manifest for hypnoglow/helm-s3:latest not found: manifest unknown: manifest unknown
```

**Comment by hypnoglow** [comment]
@austince In your opinion, what versions should the latest tag represent? The latest tagged release with the latest supported Helm? Or the master branch? 

I'm usually against this because it is pretty much unclear what **latest** is. In some repos, the latest is just bleeding-edge master builds, in other it is the latest stable version. I'm towards the latter.

But to support pulling the image without explicit tag (`docker pull hypnoglow/helm-s3`) we could support it, hoping for user responsibility to use proper tags in their "production" use cases.

**Comment by austince** [comment]
Yeah, I would agree with you that `latest` is ambiguous and should never be used in production environments, and would also agree that it makes sense as the latest stable version. I've seen `next` , or similar, used as a tag for the bleeding-edge master builds.  I think having the bleeding-edge master builds available as some tag is quite helpful when testing bug fixes/ new features before officially including them in a release.

**Comment by hypnoglow** [comment]
> I think having the bleeding-edge master builds available as some tag is quite helpful when testing bug fixes/ new features before officially including them in a release.

BTW master image is already available under tags like `master-helm2.15`.

**Comment by austince** [comment]
Great, that checks that box then.
