### ISSUE TITLE
Latest master build is failed. Is the project alive?

### ISSUE THREAD

**Issue by kivagant-ba** [hypnoglow/helm-s3#82]
https://circleci.com/gh/hypnoglow/helm-s3/391

<img src='https://camo.githubusercontent.com/f3fe9a876264a8e022d71008ea9e6e6ec822fd03/68747470733a2f2f636972636c6563692e636f6d2f67682f6879706e6f676c6f772f68656c6d2d73332e7376673f7374796c653d736869656c64' />

Latest commit e6d13b3 on Nov 8, 2018

```
Downloading and installing helm-s3 v0.8.0 ...
Invalid checksum
helm-s3 install hook failed. Please remove the plugin using 'helm plugin remove s3' and install again.
Error: plugin install hook for "s3" exited with error
Exited with code 1
```

**Comment by hypnoglow** [comment]
The project is alive indeed. I didn't pay enough attention to this repo lately, sorry about that.

Regarding the build: stable version v0.8.0 should be working fine. The master is usually "green" in the CI. And I've just changed the badge in README to reflect the master branch instead of "latest" build from any branch, which was causing confusion with "red" badge.

I'm going to close this issue. Thank you for your interest in the project.
